spaceapps/challenges/urls.py
from django.conf.urls import patterns, url

from .views import (
    Detail, 
    List, 
    Create, 
    Edit,
    Delete)


urlpatterns = patterns('',
    url(r'^$',
        List.as_view(),
        name='list_challenges'),
    url(r'^create/$',
        Create.as_view(),
        ),
    url(r'^(?P<slug>[-_\w]+)/$',
        Detail.as_view(),
        name='view_challenge',
        ),
    url(r'^(?P<slug>[-_\w]+)/edit$',
        Edit.as_view(),
        ),
    url(r'^(?P<slug>[-_\w]+)/delete$',
        Delete.as_view(),
        ),
    )

spaceapps/core/urls.py
from django.conf.urls import patterns, url

from .views import (
    Home,
    Error,
    Lost,
    No,
    )


urlpatterns = patterns('',
    url(r'^$',
        Home.as_view(),
        ),
    url(r'^500$',
        Error.as_view(),
        ),
    url(r'^404$',
        Lost.as_view(),
        ),
    url(r'^403$',
        No.as_view(),
        ),
    )

spaceapps/spaceapps/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import TemplateView

from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^selectable/', include('selectable.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls')),

    # url(r'^messages/', include('postman.urls')),
    # url(r'^notifications?/', include('notification.urls')),
    
    url(r'^account/', include('allauth.urls')),
    url(r'^challenges?/', include('challenges.urls', namespace='challenges')),
    url(r'^locations?/', include('locations.urls', namespace='locations')),
    url(r'^register/', include('registration.urls', namespace='registration')),
    url(r'^projects?/', include('projects.urls', namespace='projects')),
    url(r'^profiles?/', include('profiles.urls', namespace='profiles')),
    url(r'^awards?/', include('awards.urls', namespace='awards')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', TemplateView, { 'template': 'home.html' }),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

spaceapps/challenges/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Challenge(models.Model):
    title = models.CharField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=255, blank=True)
    slug = models.SlugField()
    description = models.TextField()
    category = models.ForeignKey('Category')
    internal = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    image = models.ImageField(upload_to="challenge", blank=True, null=True)

    class Meta:
        verbose_name_plural = "Challenges"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'view_challenge', 
            kwargs={'slug': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100, blank=True)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"
    
    def __unicode__(self):
        return self.name

class ChallengeSponsor(models.Model):
    challenge = models.ForeignKey(Challenge)
    name = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)

    def __unicode__(self):
        return self.name 

class ChallengeAuthor(models.Model):
    challenge = models.ForeignKey(Challenge)
    author = models.ForeignKey(User)
    is_public = models.BooleanField(default=False)

class ChallengeDataset(models.Model):
    challenge = models.ForeignKey(Challenge)
    title = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)
    description = models.TextField()

    def __unicode__(self):
        return self.title

spaceapps/challenges/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

import selectable.forms as selectable

from .lookups import UserLookup
from .models import (
    Challenge, 
    ChallengeSponsor,
    ChallengeAuthor,
    ChallengeDataset,)


class ChallengeForm(ModelForm):
    class Meta:
        model = Challenge

class AuthorForm(ModelForm):
    class Meta(object):
        model = ChallengeAuthor
        widgets = {
            'author': selectable.AutoCompleteSelectWidget(
                lookup_class=UserLookup
                ),
        }

SponsorFormSet = inlineformset_factory(
        Challenge, 
        ChallengeSponsor, 
        extra=1,
        )

AuthorFormSet = inlineformset_factory(
        Challenge,
        ChallengeAuthor,
        form=AuthorForm,
        extra=1,
        )

DataFormSet = inlineformset_factory(
        Challenge,
        ChallengeDataset,
        extra=1,
        )

spaceapps/challenges/views.py
import csv
from time import strftime

from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse

from braces.views import (
    LoginRequiredMixin, 
    PermissionRequiredMixin, 
    SuperuserRequiredMixin,
    )
from projects.models import Project

from .models import (
    Challenge, 
    ChallengeSponsor, 
    ChallengeAuthor, 
    ChallengeDataset,
    )
from .forms import (
    ChallengeForm, 
    SponsorFormSet,
    AuthorFormSet,
    DataFormSet,
    )


class Detail(DetailView):
    queryset = Challenge.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = {}
        context_object_name = self.get_context_object_name(self.object)
        if context_object_name:
            context[context_object_name] = self.object
        context.update(kwargs)
        context['related_projects'] = Project.objects.filter(
            challenge=self.object
            ) 
        context['sponsors'] = ChallengeSponsor.objects.filter(
            challenge=self.object
            )
        context['authors'] = ChallengeAuthor.objects.filter(
            challenge=self.object
            )
        context['data'] = ChallengeDataset.objects.filter(
            challenge=self.object
            )
        if self.request.user.is_authenticated():
            authors = ChallengeAuthor.objects.filter(
                challenge=self.object, author=self.request.user
                )
            if authors or self.request.user.has_perm(
                'challenges.change_challenge'):     
                context['is_privileged'] = True
        return super(Detail, self).get_context_data(**context)

class List(ListView):
    queryset = Challenge.objects.filter(published=True)

class Create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Challenge
    form_class = ChallengeForm
    permission_required = 'challenges.add_challenge'

    def form_valid(self, form):
        context = self.get_context_data()
        sponsor_form = context['sponsor_form']
        author_form = context['author_form']
        data_form = context['data_form']
        if (sponsor_form.is_valid() and 
            author_form.is_valid() and 
            data_form.is_valid()):
            self.object = form.save()
            sponsor_form.instance = self.object
            sponsor_form.save()
            author_form.instance = self.object
            author_form.save()
            data_form.instance = self.object
            data_form.save()
            return super(Create, self).form_valid(form)  
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(Create, self).get_context_data(**kwargs)
        if self.request.POST:
            context['sponsor_form'] = SponsorFormSet(
                self.request.POST, 
                prefix='sponsor',
                )
            context['author_form'] = AuthorFormSet(
                self.request.POST, 
                prefix='author',
                )
            context['data_form'] = DataFormSet(
                self.request.POST, 
                prefix='data',
                )
        else:
            context['sponsor_form'] = SponsorFormSet(prefix='sponsor')
            context['author_form'] = AuthorFormSet(prefix='author')
            context['data_form'] = DataFormSet(prefix='data')
        return context

class Edit(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Challenge
    form_class = ChallengeForm
    permission_required = 'challenges.change_challenge'

    def dispatch(self, request, *args, **kwargs):
        authors = ChallengeAuthor.objects.filter(
            challenge__slug=kwargs['slug'], author=request.user)
        if authors or request.user.has_perm('challenges.change_challenge'):
            return super(Edit, self).dispatch(
                request, 
                *args, 
                **kwargs
                )
        else:
            raise PermissionDenied

    def form_valid(self, form):
        """
        If the forms are valid, save the associated models.
        """
        context = self.get_context_data()
        sponsor_form = context['sponsor_form']
        author_form = context['author_form']                                    
        data_form = context['data_form']                                        
        if (sponsor_form.is_valid() and                                         
            author_form.is_valid() and                                          
            data_form.is_valid()):                                              
            self.object = form.save()                                       
            sponsor_form.instance = self.object                             
            sponsor_form.save()                                             
            author_form.instance = self.object                              
            author_form.save()                                              
            data_form.instance = self.object                                
            data_form.save()
            return super(Edit, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(Edit, self).get_context_data(**kwargs)
        if self.request.POST:
            context['sponsor_form'] = SponsorFormSet(
                self.request.POST,
                prefix='sponsor',
                instance=self.object,
                )
            context['author_form'] = AuthorFormSet(
                self.request.POST, 
                prefix='author',
                instance=self.object,
                )
            context['data_form'] = DataFormSet(
                self.request.POST, 
                prefix='data',
                instance=self.object,
                )
        else:
            context['sponsor_form'] = SponsorFormSet(
                instance=self.object, 
                prefix='sponsor',
                )
            context['author_form'] = AuthorFormSet(
                instance=self.object, 
                prefix='author',
                )
            context['data_form'] = DataFormSet(
                instance=self.object, 
                prefix='data',
                )
        return context

class Delete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Challenge
    success_url = reverse_lazy('list_challenges')
    permission_required = 'challenges.delete_challenge'

    def dispatch(self, request, *args, **kwargs):                               
        authors = ChallengeAuthor.objects.filter(                               
            challenge__slug=kwargs['slug'], author=request.user)                
        if authors or request.user.has_perm('challenges.delete_challenge'):     
            return super(Delete, self).dispatch(                         
                request,                                                        
                *args,                                                          
                **kwargs
                )                                                       
        else:                                                                   
            raise PermissionDenied

spaceapps/templates/challenges/challenge_confirm_delete.html
{% extends "base.html" %}

{% block title %}Confirm Delete{% endblock title %}

{% block content %}
<div id="content" class="row">
	<div class="twelve columns">

		Are you sure?
		<form method="POST" action="{{ request.get_full_path }}">
		  {% csrf_token %}
		  <input type="submit" value="Yes" />
		</form>
		<a href="{{ object.get_absolute_url }}">No</a>
	</div>
</div>

{% endblock content %}

spaceapps/templates/challenges/challenge_detail.html
{% extends "base.html" %}
{% load disqushmac hackpad markup md5 %}

{% block title %}{{ object.title }}{% endblock title %}
{% block main_classes %}
class="header_img"
{% endblock %}


{% block content %}

<header id="page_header" class="spacer row">
	<img src="{% if object.image %}/media/{{ object.image }}{% else %}/static/images/default.jpg{% endif %}" alt="{{ object.title }}">
	<div class="page_info twelve_columns">
		<div class="page_title row">
			<div class="twelve columns">
				<h2>{{ object.title }}</h2>
			</div>
		</div>
	</div>
</header>


<div id="content" class="row">
	<div class="twelve columns">
		<div class="row">
			<div class="twelve columns">
				<dl class="challenges tabs pill">
				  <dd class="active"><a href="#description">Description</a></dd>
				  <dd><a href="#projects">Projects</a></dd>
				  {% if user.is_authenticated %}
				  <dd><a href="#hackpad">Hackpad</a></dd>
				  {% else %}
				  <dd><a href="#">Hackpad (must be logged in)</a></dd>
				  {% endif %}
				</dl>
			</div>
		</div>
		<div class="row">
			<ul class="tabs-content">
			  <li class="active" id="descriptionTab">
				  <div class="twelve columns">
					  {% autoescape off %}
					  {{ object.description }}
					  {% endautoescape %}
					  <br>
					  <div class="row">
						  <div class="eight columns">
							  {% if data %}
							  <br>
							  <b>Datasets</b>
							  <br><br>
							  <ul class="accordion">
								  {% for i in data %}
								  {% if i.title != "Hackpad" %}
								<li{% if forloop.first %} class="active"{% endif %}>
								  <div class="title">
									  <h4>{{ i.title }}</h4>
								  </div>
								  <div class="content">
									  <a href="{{ i.url }}">{{ i.url }}</a>
									  {% if i.description == "blank" or i.description == "Blank"%}{% else %}<p>{{ i.description|linebreaks|urlize }}{% endif %}</p>
								  </div>
							  	</li>
							   {% endif %}
							  {% endfor %}
						  </ul>
						  {% endif %}
					  </div>
					  <div class="four columns">
						  <a href="{% url 'projects:create' object.slug %}" class="button full">Create Project Solving this Challenge</a>
						  <br>
						  <br>
						  <div class="panel">
							  <h3>Need help?</h3>
					  <p>Check out the <a href="#disqus_thread">comments</a> to chat with other users working on this challenge.</p>
					  </div>
					  </div>
				  </div>
			  </div>
			  <div class="twelve columns">
				  <div id="disqus_thread"></div>
				  <script type="text/javascript">
				  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
				  var disqus_config = function () {
					  // The generated payload which authenticates users with Disqus
					  this.page.remote_auth_s3 = '{% disqus_hmac userid=request.user.username  fname=request.user.first_name lname=request.user.last_name email=request.user.email %}';
					  this.page.api_key = '';
				  }
				  var disqus_shortname = ''; // required: replace example with your forum shortname
				  var disqus_identifier = '';
				  /* * * DON'T EDIT BELOW THIS LINE * * */
				  (function() {
					  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
					  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
					  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
				  })();
				  </script>
				  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
				  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
			  </div>
		  </li>
		  <li id="projectsTab" class="project_array">
			  <p>The following projects are solving this challenge:</p>			  
			  <ul class="accordion">
				  {% for i in related_projects %}
				  <li>
					  <div class="title">
						  <h3>{{ i.title }}</h3>
						  {% comment %}
						  <ul>
						   {% for i in i.list %}
						  <li>
							  <span class="has-tip" title="{{ i.user.first_name }} {{ i.user.last_name }}"><img src="http://www.gravatar.com/avatar/{{ i.user.email|md5 }}?s=40&d=retro" alt="{{ i.user.first_name }} {{ i.user.last_name }}"></span>
						  </li>
						  {% endfor %}
					  	</ul>
						{% endcomment %}
					  </div>
					  <div class="content">
						 <p>{{ i.description|truncatechars:300 }} <a href="{% url 'projects:view_project' i.slug %}">Visit Project</a></p>
					  </div>
				  </li>
				  {% endfor %}
			  </ul>
		  </li>
		  
		  {% if user.is_authenticated %}
		  <li id="hackpadTab">
			  <div class="twelve columns">
				  {% for i in data %}
				  {% if i.title = "Hackpad" %}
				  <a href="/project/create/{{object.slug}}" class="button">Create Project Solving this Challenge</a>
				  <a href="#projects">See projects currently solving this challenge</a>
				  <p>Welcome to the collaborative hackpad! You can use this open document to collaborate with others, self organize, or share important data. Please keep in mind that this document is community created and any views, opinions, or links do not reflect an official position of the Space Apps Challenge, NASA, or any of our partners.</p>
				  <p>Building a team or looking for one to join? There's a Matchmaking section at the bottom of the document to help in gathering great minds together!</p>
				  <div id="hackpad" style="min-height:600px"></div>
				  <script src="https://hackpad.com/static/hackpad.js"></script>
				  <script>
				  hackpad.render_url('#hackpad', '{% hackpad padId=i.description fname=request.user.first_name|iriencode lname=request.user.last_name|iriencode email=request.user.email %}');
				  </script>
				  {% endif %}
				  {% endfor %}
			  </div>
		  </li>
		  {% endif %}
	  </ul>
	</div>
</div>

{% endblock content %}

spaceapps/templates/challenges/challenge_form.html
{% extends 'base.html' %}
{% block content %}
{{ author_form.media.css }}

<div id="content" class="row">
	<div class="twelve columns challenge edit">
		
		<form method='post' action=''>
			<div id="wysihtml5-toolbar" style="display: none;"><div id="toolbar-styling" class="eight columns"><a data-wysihtml5-command="bold"><i class="icon-bold"></i> bold</a><a data-wysihtml5-command="italic"><i class="icon-italic"></i> italic</a><a data-wysihtml5-command="insertOrderedList"><i class="icon-list-ol"></i> insert ordered list</a>
			  					 <a data-wysihtml5-command="insertUnorderedList"><i class="icon-list-ul"></i> insert unordered list</a>
			  					 <a data-wysihtml5-command="createLink"><i class="icon-link"></i> insert link</a>
			  					 <div data-wysihtml5-dialog="createLink" style="display: none;">
			  						 <label>
			  							 Link:
			  							 <input data-wysihtml5-dialog-field="href" value="http://" class="text">
			  						 </label>
			  						 <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
			  					 </div>
			  				 </div>
			  				 <div class="two columns offset-by-two">
			  					 <a data-wysihtml5-action="change_view" href="javascript:;" unselectable="on" class="wysihtml5-action-active" id="htmlswitch">switch to html</a>
			  				 </div>
			  			 </div>
		  {% csrf_token %}

		    {{ form.as_p }}

		  {{ sponsor_form.management_form }}
		    {% for form in sponsor_form %}
		      <div id='sponsor'>
		        {{ form.as_p }}
		      </div>
		    {% endfor %}
		  {{ author_form.management_form }}
		    {% for form in author_form %}
		      <div id='author'>
		        {{ form.as_p }}
		      </div>
		    {% endfor %}
		  {{ data_form.management_form }}
		    {% for form in data_form %}
		      <div id='data'>
		        {{ form.as_p }}
		      </div>
		    {% endfor %}
		  <input type='submit' class='button' value='Submit'>
		</form>
	</div>
</div>

<script src='/static/js/jquery.formset.min.js'></script>
<script type="text/javascript">
  $(function() {
    $('#sponsor').formset({ 
      prefix: '{{ sponsor_form.prefix }}' 
    }); 
    $('#author').formset({
      prefix: '{{ author_form.prefix }}',
      added: function(row) {
                        bindSelectables($(row));
                }
    });
    $('#data').formset({ 
      prefix: '{{ data_form.prefix }}' 
    }); 
  })
</script>
{{ author_form.media.js }}
{% endblock %}

{% block js %}
<script type="text/javascript" src="/static/js/jquery.slugify.js"></script>
<script type="text/javascript"> 
$(document).ready(function () {
	$('input#id_slug').slugify('input#id_title');
}); 
		
</script>

<script src="/static/js/wysihtml5/advanced.js"></script>
<script src="/static/js/wysihtml5/wysihtml5-0.3.0.min.js"></script>
<script>
var editor = new wysihtml5.Editor("id_description", { // id of textarea element
  toolbar:      "wysihtml5-toolbar", // id of toolbar element
  parserRules:  wysihtml5ParserRules // defined in parser rules set 
});
</script>

{% endblock %}

spaceapps/templates/challenges/challenge_list.html
{% extends "base.html" %}

{% block title %}Challenges{% endblock title %}

{% block main_classes %}
class="header_img"
{% endblock %}

{% block content %}

<header id="page_header" class="spacer row">
	<img src="/static/images/5.png" alt="Challenges">
	<div class="page_info twelve_columns">
		<div class="page_title row">
			<div class="twelve columns">
				<h2>Challenges</h2>
			</div>
		</div>
	</div>
</header>

<div id="content" class="row">
	<div class="twelve columns">
		<div class="row">
			<div class="seven columns">
				<br>

				<p>The dynamic grid challenges page is the central location to engage teams in the needs of your mission. Each individual challenge page provides functionality for an image, hashtag, background content, challenge description, functional specifications, associated datasets and email service to contact the challenge owner. Each page is also set up for threaded comments via Disqus and an associated real-time wiki via Hackpad to enable collaborative engagement. Project (solution) pages can be initiated directly from challenge pages</p>
				<p>Potential descriptive content here could also include:</p>
			</div>
			<div class="five columns">
				<div class="video flex-video widescreen">
					<iframe width="560" height="315" src="//www.youtube.com/embed/KaOC9danxNo" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
		<h3>How do I choose a challenge?</h3>
		<p>[Describe here how your participants will choose or be assigned to challenges]</p>
		
		<h3>How do I find a team?</h3>
		<p>[How will collaboration happen?]</p>
		
		<h3>How will I submit a solution?</h3>
		<p>[Describe your solution submission process.]</p>
	
		<div class="row">
			<div class="eight columns offset-by-four">
				<ul id="filters" class="challenge tabs pill">
					<li class="active"><a href="#" data-filter="*">All</a></li>
					<li><a href="#" data-filter=".software">Software</a></li>
					<li><a href="#" data-filter=".hardware">Hardware</a></li>
					<li><a href="#" data-filter=".citizen-science">Citizen Science</a></li>
					<li><a href="#" data-filter=".data-visualization">Data Visualization</a></li>
				</ul>
			</div>
		</div>
	  	<ul id="challenge_array" class="block_array block-grid two-up mobile challenge_array">
			{% for i in object_list %}
		  		<li class="{{ i.category.slug }}">
					<div class="main">
						<a href="{% url 'challenges:view_challenge' i.slug %}"><img src="{% if i.image %}/media/{{ i.image }}{% else %}/static/images/default.jpg{% endif %}" alt="{{ i.title }}">
						<h3>{{ i.title }}</h3></a>
						{{ i.subtitle }}
					</div>		
				</li>
			{% endfor %}
	  	</ul>

		{% comment %}
		<ul>
		
		</ul>
		{% endcomment %}
	</div>
</div>

{% endblock content %}

{% block js %}
<script src="/static/js/jquery.isotope.min.js"></script>
<script>
// cache container
var $container = $('#challenge_array');
// initialize isotope
$container.imagesLoaded( function(){
  $container.isotope({
    // options...
  });
});

// filter items when filter link is clicked
$('#filters a').click(function(){
	$('#filters li').removeClass('active');
	$(this).parent().addClass('active');
	var selector = $(this).attr('data-filter');
	$container.isotope({ filter: selector });
	return false;
});

</script>
{% endblock %}