spaceapps/challenges/urls.py
from django.conf.urls import patterns, url

from .views import (
    Detail, 
    List, 
    Create, 
    Edit,
    Delete)


urlpatterns = patterns('',
    url(r'^$',
        List.as_view(),
        name='list_challenges'),
    url(r'^create/$',
        Create.as_view(),
        ),
    url(r'^(?P<slug>[-_\w]+)/$',
        Detail.as_view(),
        name='view_challenge',
        ),
    url(r'^(?P<slug>[-_\w]+)/edit$',
        Edit.as_view(),
        ),
    url(r'^(?P<slug>[-_\w]+)/delete$',
        Delete.as_view(),
        ),
    )

spaceapps/core/urls.py
from django.conf.urls import patterns, url

from .views import (
    Home,
    Error,
    Lost,
    No,
    )


urlpatterns = patterns('',
    url(r'^$',
        Home.as_view(),
        ),
    url(r'^500$',
        Error.as_view(),
        ),
    url(r'^404$',
        Lost.as_view(),
        ),
    url(r'^403$',
        No.as_view(),
        ),
    )

spaceapps/projects/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (
    List,
    Detail,
    VoteBox,
    Judging,
    Create,
    Edit,
    Delete,
    )


urlpatterns = patterns('',
    url(r'^$',
        List.as_view(),
        name='list',
        ),
    url(r'^(judging)/$',
        Judging.as_view(),
        name='judging',
        ),
    url(r'^create/(?P<slug>[-_\w]+)?$',
        Create.as_view(),
        name='create',
        ),
    url(r'^(?P<slug>[-_\w]+)/join$',
        Detail.as_view(),
        name='view_project',
        ),
    url(r'^(?P<slug>[-_\w]+)/votebox$',
        VoteBox.as_view(),
        name='vote_box',
        ),
    url(r'^(?P<slug>[-_\w]+)/$',
        Detail.as_view(),
        name='view_project',
        ),
    url(r'^(?P<slug>[-_\w]+)/edit$',
        Edit.as_view(),
        name='edit',
        ),
    url(r'^(?P<slug>[-_\w]+)/delete$',
        Delete.as_view(),
        name='delete',
        ),
    )

spaceapps/spaceapps/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import TemplateView

from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^selectable/', include('selectable.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls')),

    # url(r'^messages/', include('postman.urls')),
    # url(r'^notifications?/', include('notification.urls')),
    
    url(r'^account/', include('allauth.urls')),
    url(r'^challenges?/', include('challenges.urls', namespace='challenges')),
    url(r'^locations?/', include('locations.urls', namespace='locations')),
    url(r'^register/', include('registration.urls', namespace='registration')),
    url(r'^projects?/', include('projects.urls', namespace='projects')),
    url(r'^profiles?/', include('profiles.urls', namespace='profiles')),
    url(r'^awards?/', include('awards.urls', namespace='awards')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', TemplateView, { 'template': 'home.html' }),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

spaceapps/challenges/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Challenge(models.Model):
    title = models.CharField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=255, blank=True)
    slug = models.SlugField()
    description = models.TextField()
    category = models.ForeignKey('Category')
    internal = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    image = models.ImageField(upload_to="challenge", blank=True, null=True)

    class Meta:
        verbose_name_plural = "Challenges"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'view_challenge', 
            kwargs={'slug': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100, blank=True)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"
    
    def __unicode__(self):
        return self.name

class ChallengeSponsor(models.Model):
    challenge = models.ForeignKey(Challenge)
    name = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)

    def __unicode__(self):
        return self.name 

class ChallengeAuthor(models.Model):
    challenge = models.ForeignKey(Challenge)
    author = models.ForeignKey(User)
    is_public = models.BooleanField(default=False)

class ChallengeDataset(models.Model):
    challenge = models.ForeignKey(Challenge)
    title = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)
    description = models.TextField()

    def __unicode__(self):
        return self.title

spaceapps/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from challenges.models import Challenge

class Project(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()
    challenge = models.ForeignKey(Challenge, blank=True, null=True)
    source_url = models.URLField(max_length=200, blank=True)
    source_url_check_bypass = models.BooleanField(default=False)
    license = models.ForeignKey('License')
    video = models.URLField(max_length=200, blank=True)
    nominated = models.BooleanField(default=False) 
    remove_from_judging = models.BooleanField(default=False)
    reason_for_disqualification = models.TextField(
        max_length=500, 
        null=True, 
        default=None, 
        blank=True,
        )
    finalist = models.BooleanField(default=False)
    hashtag = models.CharField(
        max_length=100, 
        null=True, 
        default=None, 
        blank=True,
        )
    short_description = models.TextField(
        max_length=500, 
        null=True, 
        default=None, 
        blank=True,
        )

    class Meta:                                                                 
        verbose_name_plural = "Projects"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'projects:view_project', 
            kwargs={'slug': self.slug})

class License(models.Model):                                                   
    name = models.CharField(max_length=100, blank=True)                     
    url = models.URLField(max_length=200, blank=True)                          
                                                                                
    class Meta:                                                                 
        verbose_name_plural = "Licenses"
    
    def __unicode__(self):                                                      
        return self.name                                                    

class Team(models.Model):
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    request_text = models.TextField(blank=True)
    approved = models.BooleanField(default=False)
    
    class Meta:                                                                 
        verbose_name_plural = "Team"

class Resource(models.Model):                                           
    project = models.ForeignKey(Project)                                    
    title = models.CharField(max_length=100, blank=True)                        
    url = models.URLField(max_length=200, blank=True)                          
                                                                                
    class Meta:                                                                 
        verbose_name_plural = "Resources"
    
    def __unicode__(self):                                                      
        return self.title

spaceapps/projects/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

import selectable.forms as selectable

from .lookups import UserLookup
from .models import (
    Project, 
    Team,
    Resource,
    )


class LocationForm(ModelForm):
    class Meta:
        model = Project 

class TeamForm(ModelForm):
    class Meta(object):
        model = Team 
        exclude = ('request_text', 'approved',)
        widgets = {
            'user': selectable.AutoCompleteSelectWidget(
                lookup_class=UserLookup)
            }

TeamFormSet = inlineformset_factory(
        Project, 
        Team, 
        form = TeamForm,
        extra=1,
        )

ResourceFormSet = inlineformset_factory(
        Project,
        Resource,
        extra=1,
        )

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = (
            'category', 
            'source_url_check_bypass', 
            'nominated', 
            'remove_from_judging', 
            'reason_for_disqualification', 
            'finalist', 
            'hashtag', 
            'award_class',
            )

spaceapps/projects/views.py
from time import strftime
import csv

from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse

from awards.models import LocalAward, Nomination
from braces.views import (
    LoginRequiredMixin, 
    PermissionRequiredMixin, 
    SuperuserRequiredMixin,
    )
from challenges.models import Challenge
from profiles.models import Profile
from registration.models import Registration

from .models import Project, Team, Resource
from .forms import (
    TeamFormSet,
    ResourceFormSet,
    ProjectForm,
    )


class Detail(DetailView):
    model = Project 

    def get_context_data(self, **kwargs):
        context = {}
        context_object_name = self.get_context_object_name(self.object)
        if context_object_name:
            context[context_object_name] = self.object
        context.update(kwargs)
        context['resources'] = Resource.objects.filter(
            project=self.object
            )
        context['team'] = Team.objects.filter(
            project=self.object
            )
        context['awards'] = LocalAward.objects.filter(
            project=self.object
            )
        context['nomination'] = Nomination.objects.filter(project=self.object)
        return super(Detail, self).get_context_data(**context) 

class List(ListView):
    queryset = Project.objects.order_by('challenge').reverse()

    def get_context_data(self, **kwargs):
        context = super(List, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['user_projects'] = Team.objects.filter(
                user=self.request.user
                )
        return context

class Create(LoginRequiredMixin, CreateView):
    model = Project

    def form_valid(self, form):
        context = self.get_context_data()
        team_form = context['team_form']
        resource_form = context['resource_form']
        if (team_form.is_valid() and resource_form.is_valid()): 
            self.object = form.save()
            team_form.instance = self.object
            team_form.save(commit=False)
            for i in team_form:
                try: 
                    i.instance.project.id
                except:
                    pass
                else:
                    i.instance.approved = True
                    i.save()
            resource_form.instance = self.object
            resource_form.save()
            submitter = Team(
                project = self.object,
                user = self.request.user,
                approved = True,
                )
            submitter.save()
            return super(Create, self).form_valid(form)  
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_initial(self):
        initial = super(Create, self).get_initial()
        if self.kwargs['slug']:
            initial['challenge'] = Challenge.objects.get(
                slug=self.kwargs['slug'],
                )
        return initial

    def get_context_data(self, **kwargs):
        context = super(Create, self).get_context_data(**kwargs)
        if self.request.POST:
            context['team_form'] = TeamFormSet(
                self.request.POST, 
                prefix='team',
                )
            context['resource_form'] = ResourceFormSet(
                self.request.POST, 
                prefix='resource',
                )
        else:
            context['team_form'] = TeamFormSet(prefix='team')
            context['resource_form'] = ResourceFormSet(prefix='resource')
        return context

class Edit(LoginRequiredMixin, UpdateView):
    model = Project 
    form_class = ProjectForm

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        context = self.get_context_data()
        team_form = context['team_form']
        resource_form = context['resource_form']
        if (resource_form.is_valid()):
            self.object = form.save()
            team_form.instance = self.object
            team_form.save()
            resource_form.instance = self.object
            resource_form.save()
            return super(Edit, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(Edit, self).get_context_data(**kwargs)
        if self.request.POST:
            context['team_form'] = TeamFormSet(
                self.request.POST, 
                prefix='team',
                instance=self.object,
                )
            context['resource_form'] = ResourceFormSet(
                self.request.POST, 
                prefix='resource',
                instance=self.object,
                )
        else:
            context['team_form'] = TeamFormSet(
                instance=self.object, 
                prefix='team',
                )
            context['resource_form'] = ResourceFormSet(
                instance=self.object, 
                prefix='resource',
                )
        return context

class Delete(LoginRequiredMixin, DeleteView):
    model = Project 
    success_url = reverse_lazy('list')

class Judging(ListView):
    queryset = Project.objects.filter(finalist=True).order_by('category')
#    template_name = 'projects/project_judging.html'

class VoteBox(Detail):
    template_name = 'projects/project_votebox.html'

spaceapps/templates/projects/project_form.html
{% extends 'base.html' %}

{% block title %}Edit Project{% endblock title %}


{% block header %}
<header id="page_header" class="nobanner row">
	<div class="eight columns">
		<h2>Edit Project</h2>
	</div>
</header>
{% endblock %}


{% block content %}
{{ team_form.media.css }}
<div id="content" class="row">
	<div class="twelve columns">
		
		{% if request.user.is_staff %}
		<div class="panel">
			<h3>Super Secret Admin Features</h3>
			<div class="row">
				{% if not object.video %}
				<div class="twelve columns">
					<div class="alert-box alert">
					  This project is missing a video.
					  <a href="" class="close">&times;</a>
					</div>
				</div>
				{% endif %}
				{% if not object.short_description %}
				<div class="twelve columns">
					<div class="alert-box alert">
					  This project is missing a short overview.
					  <a href="" class="close">&times;</a>
					</div>
				</div>
				{% endif %}
				{% if not object.source_url %}
				<div class="twelve columns">
					<div class="alert-box alert">
					  This project is missing a source URL.
					  <a href="" class="close">&times;</a>
					</div>
				</div>
				{% endif %}
				{% if not object.source_url_check_bypass %}
				{% if not "github" in object.source_url %}
				{% if not "bitbucket" in object.source_url %}
				{% if not "code.google" in object.source_url %}
				<div class="twelve columns">
					<div class="alert-box">
					  The source URL for this project may not actually be Source Code. You should <a href="#source_url">double check it and bypass if needed.</a>
					</div>
				</div>
				{% endif %}
				{% endif %}
				{% endif %}
				{% endif %}
			</div>
			{% comment %}
			<div class="row">
				<div class="four columns field hashtag">
					<label for="id_hashtag">Hashtag</label>
				    <div class="row collapse">
						<div class="one mobile-one columns">
							<span class="prefix">#</span>
						</div>
						<div class="eleven mobile-three columns">
							{{ form.hashtag }}
						</div>
					</div>
					<span class="detail">The project hashtag should not include #.</span>
					{{ form.hashtag.errors }}
				</div>
				<div class="eight columns field category">
					<label for="id_category">Category</label>
					{{ form.category }}
					{{ form.category.errors }}
				</div>
			</div>
			<div class="row">
				<div class="four columns field remove_from_judging">
					<label for="id_remove_from_judging">Remove from judging?
					{{ form.remove_from_judging }}</label>
					{{ form.remove_from_judging.errors }}
					<span class="detail">This project does not qualify for global judging and public voting.</span>
				</div>
				<div class="four columns end field finalist">
					<label for="id_finalist">Finalist?
					{{ form.finalist }}</label>
					{{ form.finalist.errors }}
					<span class="detail">Note: A project is a finalist if it has been promoted to the final round of judging. Projects do <b>not</b> need to be marked as finalists in order to qualify for public voting</span>
				</div>
			</div>
			<div class="row">
				<div class="eight columns field reason_for_disqualification">
					<label for="id_reason_for_disqualification">Reason for disqualification</label>
					{{ form.reason_for_disqualification }}
					{{ form.reason_for_disqualification.errors }}
				</div>
			</div>
			{% endcomment %}
		</div>
		{% endif %}
		{% if object.remove_from_judging %}
		{% if object.reason_for_disqualification %}
		<div class="panel">
			<h3>Oh no!</h3>
			<p>Your project was nominated for a global award but you were disqualified due to the following:<br>
				<br>
				<em>{{ object.reason_for_disqualification }}</em></p>
		</div>
		<br>
		{% endif %}
		{% endif %}
		<form class="custom project edit" method="post">
			{% csrf_token %}
			<div class="field title">
				<label for="id_title">Title <span class="required">Required</span></label>
				{{ form.title }}
				{{ form.title.errors }}
				{% if form.slug.errors %}<br><br>/project/{{ form.slug }}{% else %}<div class="inline"><div class="url">/project/{{ form.slug }}</div></div>{% endif %}
				{{ form.slug.errors }}
				<span class="detail">NOTE: If you change your project's URL, all existing links to your project will no longer work!</span>
			</div>
			
			<div class="field challenge">
				<label for="id_challenge">Challenge<br><span class="detail">If this project is in response to a specific <a href="/challenges">Challenge</a>, select it here.</span></label>
				{{ form.challenge }}
				{{ form.challenge.errors }}
			</div>
			
			<div class="field license">
				<label for="id_license">License <span class="required">Required</span><br><span class="detail">The license under which your work is released. All submissions must be licensed under an <a href="http://opensource.org/licenses/alphabetical">OSI Approved License</a> to be considered for judging.</span></label>
				{{ form.license }}
				{{ form.license.errors }}
			</div>
			
			
			<div class="field short_description">
				<label for="id_short_description">Short Overview <span class="required">Required if nominated for global judging</span><br><span class="detail">Clearly describe your project in 500 characters or fewer.</span></label>
				{{ form.short_description}}
				<span class="charsLeft"></span>
				{{ form.short_description.errors }}
			</div>
			
			<div class="field description">
				<label for="id_description">Description <span class="required">Required</span><br><span class="detail">An explaination of what your project aims to achieve, and how. This field takes <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown</a> for styling.</span></label>
				{{ form.description}}
				{{ form.description.errors }}
			</div>
			
			<div class="field vidupload">
				<label for="id_video">Video <span class="required">Required if nominated for global judging</span><br><span class="detail">Please include a link to a short, 2 minute video describing your work. This field should be a URL to YouTube or Vimeo, eg. <a href="http://www.youtube.com/watch?v=jmHgN9VE9OY">http://www.youtube.com/watch?v=jmHgN9VE9OY</a></span></label>
				{{ form.video }}
				{{ form.video.errors }}
			</div>
			
			<div class="field source" id="source_url">
				<label for="id_source_url">Source Code/Main Project URL <span class="required">Required</span><br><span class="detail">A URL to where the source code or main project may be found. If your project is software, this should be a link to the raw source code. <a href="http://www.github.com">GitHub</a> is the preferred location for all projects</span></label>
				{{ form.source_url }}
				{{ form.source_url.errors }}
				{% if object.source_url %}
				{% if not "github" in object.source_url %}
				{% if not "bitbucket" in object.source_url %}
				{% if not "code.google" in object.source_url %}
				{% comment %}
				<label for="id_source_url_check_bypass">{% if object.source_url_check_bypass %}Source URL check has been overriden. Uncheck to restore to normal operation{% else %}This project may not meet Source Code URL Requirements. Check to manually override:{% endif %} {{ form.source_url_check_bypass }}</label>{{ form.source_url_check_bypass.errors }}
				{% endcomment %}
				{% endif %}
				{% endif %}
				{% endif %}
				{% endif %}
								
			</div>
			
			<div class="field">
				<h3>Project Members</h3>
				<p>You can add additional project members by searching for them <b>using the email address they have registered with</b> in this form.</p>
				<div id="team">
				{{ team_form.management_form }}
					{% for form in team_form %}
						<div class="member">
							{{ form.as_p }}
						</div>
					{% endfor %}
				</div>
			</div>
			
			<div class="field resources">
				<h3>Resources</h3>
				<p>You can add additional resources to your project as well. These may include presentations, source code, images, videos, etc. Simply provide a title and a URL</p>
				{{ resource_form.management_form }}
				{% for form in resource_form %}
				<div class='resource'>
				{{ form.as_p }}
				</div>
				{% endfor %}
			</div>
			<input type='submit' class='button' value='Submit'>
		</form>	
	</div>
</div>

{% endblock %}

{% block js %}
<script src="/static/js/jquery.sify.js"></script>
<script>
$('#id_slug').slugify('#id_title');
</script>

{% if request.user.is_staff %}
<script type="text/javascript">

$(document).ready(function() {
	reason_for_disqualification_hide();
});

$("div.remove_from_judging").click(function() {
	$('div.reason_for_disqualification').toggle();
});

function reason_for_disqualification_hide() {
	if ($('div.remove_from_judging span').hasClass('checked')) {
		$("div.reason_for_disqualification").hide();
	}
	else if (!$('div.remove_from_judging span').hasClass('checked')){
		$("div.reason_for_disqualification").show();
	}
}
</script>
{% endif %}
<script src='/static/js/jquery.formset.min.js'></script>
<script type="text/javascript">
  $(function() {
    $('.member').formset({ 
      prefix: '{{ team_form.prefix }}',
      added: function(row) {
                    bindSelectables( $(row) );}
    }); 
    $('.resource').formset({ 
      prefix: '{{ resource_form.prefix }}' 
    }); 
  })
</script>
<script type="text/javascript">
$(document).ready(function() {
	$('a.add-row').addClass('button');
});
  
</script>
<script>
function updateCountdown() {
    var remaining = 500 - jQuery('#id_short_description').val().length;
    jQuery('.charsLeft').text(remaining + ' characters remaining.');
	if (remaining<0) {
		jQuery('.charsLeft').css("color", "red");
	}
	else {
		jQuery('.charsLeft').removeAttr('style');
	}
}
jQuery(document).ready(function($) {
    updateCountdown();
    $('#id_short_description').change(updateCountdown);
    $('#id_short_description').keyup(updateCountdown);
});
</script>
{{ team_form.media.js }}
{% endblock %}

spaceapps/templates/projects/project_judging.html
{% extends "base.html" %}
{% load micawber_tags %}

{% block title %}Judging{% endblock title %}

{% block header %}
<header id="page_header" class="nobanner row">
	<div class="eight columns">
		<h2>Project Judging</h2>
	</div>
</header>
{% endblock %}

{% block content %}

<div id="content" class="row">
	<div class="twelve columns">
       {% regroup object_list by category as by_category %}
       {% for i in by_category %}
	   	{% if not i.grouper.name %}
			<h2>No Associated Category</h2>
			<hr>
		{% else %}
			<h2>{{ i.grouper.name }}</h2>
		{% endif %}
		{% for i in i.list %}
		<div class="row">
			<div class="five columns">
				<div class="flex-video widescreen {% if "vimeo" in i.video %}vimeo{% endif %}">
					{{ i.video|oembed }}
				</div>
			</div>
			<div class="seven columns">
				<h4>#{{ i.hashtag }}</h4>
				{{ i.short_description|truncatechars:503 }}<br><br>
				<a class="button" href="{% url 'projects:view_project' i.slug %}" target="_blank">View this project</a>
			</div>
		</div>
		<hr>
		{% endfor %}
	   {% endfor %}
   </div>
</div>
{% endblock content %}

spaceapps/templates/projects/project_list.html
{% extends "base.html" %}
{% load md5 markup %}

{% block title %}Projects{% endblock title %}

{% block header %}
<header id="page_header" class="nobanner row">
	<div class="eight columns">
		<h2>Projects</h2>
	</div>
</header>
{% endblock %}

{% block content %}

<div id="content" class="row">
	<div class="twelve columns">
		<div class="row">
			<div class="seven columns">
				<br>
				<p>This page indexes each project currently being worked on. You can click the button below to create your own.</p>
				<a href="{% url 'projects:create' %}" class="button">Create Project</a>
			</div>
			<div class="five columns">
				<div class="video flex-video widescreen">
					<iframe width="560" height="315" src="//www.youtube.com/embed/KaOC9danxNo" frameborder="0" allowfullscreen=""></iframe>
				</div>
			</div>
		</div>
		
	    {% if request.user.is_authenticated %}
	     <h3>My Projects</h3>
	     <ul>
	       {% for i in user_projects %}
	       <a href="{% url 'projects:view_project' i.project.slug %}"><li>{{ i.project.title.title }}</li></a>
	       {% endfor %}
	     </ul>
	     {% endif %}
		 <br>
     <hr>
     <h3>Project by Challenge</h3>
     <ul class="accordion">
       {% regroup object_list by challenge as by_challenge %}
       {% for i in by_challenge %}
       <li>
       <div class='title'>
         <h3> {% if not i.grouper.title %}
           No Associated Challenge
           {% else %}
           {{ i.grouper.title.title }} 
           {% endif %}</h3>
       </div>
     <div class='content'>
     <ul>
       {% for i in i.list %}
       <li><a href="{% url 'projects:view_project' i.slug %}">{{ i.title.title }}</a></li>
       {% endfor %}
     </ul>
 </div>
 </li>
 {% endfor %}
 </ul>
 {% comment %}
		 <h3>All Projects</h3>
		  <ul class="accordion">
			  {% for i in object_list %}
			  <li>
				  <div class="title">
					  <h3>{{ i.title }}</h3>
					  <ul>
					  {% for i in i.team %}
					  <li>
						  <span class="has-tip" title="{{ member.user.first_name }} {{ i.user.last_name }}"><img src="http://www.gravatar.com/avatar/{{ i.user.email|md5 }}" alt="{{ i.user.first_name }} {{ i.user.last_name }}"></span>
					  </li>
					  {% endfor %}
				  	</ul>
				  </div>
				  <div class="content">
					 <p>{{ i.description|truncatechars:300 }} <a href="{% url 'projects:view_project' i.slug %}">Visit Project</a></p>
				  </div>
			  </li>
			  {% endfor %}
      </ul>
      {% endcomment %}
	  </div>
</div>
{% endblock content %}

spaceapps/templates/projects/project_votebox.html
{% load micawber_tags %}
<div class="row">
	<div class="vid">
		<div class="flex-video widescreen {% if "vimeo" in object.video %}vimeo{% endif %}">
			{{ object.video|oembed }}
		</div>
	</div>
	<div class="text">
		<h2>#{{ object.hashtag }}</h2>
		<p>{{ object.short_description|truncatechars:503 }} <a href="{% url 'projects:view_project' object.slug %}">read more</a></p>
		<a class="button success large" href="">Vote Now</a> <a class="button secondary large" id="next_project" href="#">Next Project</a>
	</div>
</div>