spaceapps/core/urls.py
from django.conf.urls import patterns, url

from .views import (
    Home,
    Error,
    Lost,
    No,
    )


urlpatterns = patterns('',
    url(r'^$',
        Home.as_view(),
        ),
    url(r'^500$',
        Error.as_view(),
        ),
    url(r'^404$',
        Lost.as_view(),
        ),
    url(r'^403$',
        No.as_view(),
        ),
    )

spaceapps/profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *

from profiles import views

urlpatterns = patterns('',
                       url(r'^create/$',
                           views.create_profile,
                           name='profiles_create_profile',
                           ),
                       url(r'^edit/$',
                           views.edit_profile,
                           name='profiles_edit_profile'),
                       url(r'^(?P<username>[\w\.\-\+_@]+)/$',
                           views.profile_detail,
                           name='profiles_profile_detail',
                           ),
                       url(r'^$',
                           views.profile_list,
                           name='profiles_profile_list',
                           ),
                       )

spaceapps/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class Background(models.Model):
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

BACKGROUND = (                                                              
        ('1', 'Developer'),                                                       
        ('2', 'Designer/Artist'),                                                   
        ('3', 'Student'),
        ('4', 'Subject Matter Expert'),
        ('5', 'Entrepreneur'),                                                   
    ) 

class Profile(models.Model):
    user = models.OneToOneField(User)
    allow_contact = models.BooleanField(default=False,
        help_text=('Designates that this user may be contacted by email.'))
    background = models.ManyToManyField(Background, blank=True)
    skype = models.CharField(max_length=32, blank=True)
    twitter = models.CharField(max_length=15, blank=True)
    github = models.CharField(max_length=32, blank=True)
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=32, blank=True)
    country = models.CharField(max_length=32, blank=True)

    class Meta:
        verbose_name = ('profile')
        verbose_name_plural = ('profiles')

    def __unicode__(self):
        return unicode(self.user)

spaceapps/profiles/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

from .models import Profile

class ProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['email'].initial = self.instance.user.email
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except User.DoesNotExist:
            pass

    email = forms.EmailField(label="Primary email",help_text='')
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = Profile
        exclude = ('user',)

    def save(self, *args, **kwargs):
        """
        Update the primary email address on the related User object as well.
        """
        u = self.instance.user
        u.email = self.cleaned_data['email']
        u.save()
        profile = super(ProfileForm, self).save(*args,**kwargs)
        return profile


class RegistrationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, label='First Name')           
    last_name = forms.CharField(max_length=30, label='Last Name')

    def save(self, user):                                                     
        profile = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']                     
        user.last_name = self.cleaned_data['last_name']                       
        user.save()
        profile.user = user
        profile.save()
        self.save_m2m()

    class Meta:
        model = Profile
        exclude = ["user",]
        widgets = {'background': forms.CheckboxSelectMultiple}

spaceapps/profiles/views.py
"""
Views for creating, editing and viewing site-specific user profiles.

"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
# from django.views.generic.list_detail import object_list
from django.views.generic import ListView
from profiles.forms import ProfileForm
from profiles import utils


def create_profile(request, form_class=None, success_url=None,
                   template_name='profiles/create_profile.html',
                   extra_context=None):
    """
    Create a profile for the current user, if one doesn't already
    exist.
    
    If the user already has a profile, as determined by
    ``request.user.get_profile()``, a redirect will be issued to the
    :view:`profiles.views.edit_profile` view. If no profile model has
    been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and creating the user
        profile. This form class must define a method named
        ``save()``, implementing the same argument signature as the
        ``save()`` method of a standard Django ``ModelForm`` (this
        view will call ``save(commit=False)`` to obtain the profile
        object, and fill in the user before the final save). If the
        profile object includes many-to-many relations, the convention
        established by ``ModelForm`` of using a method named
        ``save_m2m()`` will be used, and so your form class should
        also define this method.
        
        If this argument is not supplied, this view will use a
        ``ModelForm`` automatically generated from the model specified
        by ``AUTH_PROFILE_MODULE``.
    
    ``success_url``
        The URL to redirect to after successful profile creation. If
        this argument is not supplied, this will default to the URL of
        :view:`profiles.views.profile_detail` for the newly-created
        profile object.
    
    ``template_name``
        The template to use when displaying the profile-creation
        form. If not supplied, this will default to
        :template:`profiles/create_profile.html`.
    
    **Context:**
    
    ``form``
        The profile-creation form.
    
    **Template:**
    
    ``template_name`` keyword argument, or
    :template:`profiles/create_profile.html`.
    
    """
    try:
        profile_obj = request.user.get_profile()
        return HttpResponseRedirect(reverse('profiles:profiles_edit_profile'))
    except ObjectDoesNotExist:
        pass
    
    #
    # We set up success_url here, rather than as the default value for
    # the argument. Trying to do it as the argument's default would
    # mean evaluating the call to reverse() at the time this module is
    # first imported, which introduces a circular dependency: to
    # perform the reverse lookup we need access to profiles/urls.py,
    # but profiles/urls.py in turn imports this module.
    #
    
    if success_url is None:
        success_url = reverse('profiles:profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()
    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            profile_obj = form.save(commit=False)
            profile_obj.user = request.user
            profile_obj.save()
            if hasattr(form, 'save_m2m'):
                form.save_m2m()
            return HttpResponseRedirect(success_url)
    else:
        form = form_class()
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value
    
    return render_to_response(template_name,
                              { 'form': form },
                              context_instance=context)
create_profile = login_required(create_profile)

def edit_profile(request, form_class=ProfileForm, success_url=None,
                 template_name='profiles/edit_profile.html',
                 extra_context=None):
    """
    Edit the current user's profile.
    
    If the user does not already have a profile (as determined by
    ``User.get_profile()``), a redirect will be issued to the
    :view:`profiles.views.create_profile` view; if no profile model
    has been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and editing the user
        profile. This form class must operate similarly to a standard
        Django ``ModelForm`` in that it must accept an instance of the
        object to be edited as the keyword argument ``instance`` to
        its constructor, and it must implement a method named
        ``save()`` which will save the updates to the object. If this
        argument is not specified, this view will use a ``ModelForm``
        generated from the model specified in the
        ``AUTH_PROFILE_MODULE`` setting.
    
    ``success_url``
        The URL to redirect to following a successful edit. If not
        specified, this will default to the URL of
        :view:`profiles.views.profile_detail` for the profile object
        being edited.
    
    ``template_name``
        The template to use when displaying the profile-editing
        form. If not specified, this will default to
        :template:`profiles/edit_profile.html`.
    
    **Context:**
    
    ``form``
        The form for editing the profile.
        
    ``profile``
         The user's current profile.
    
    **Template:**
    
    ``template_name`` keyword argument or
    :template:`profiles/edit_profile.html`.
    
    """
    try:
        profile_obj = request.user.get_profile()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('profiles:profiles_create_profile'))
    
    #
    # See the comment in create_profile() for discussion of why
    # success_url is set up here, rather than as a default value for
    # the argument.
    #
    
    if success_url is None:
        success_url = reverse('profiles:profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()
    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES, instance=profile_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)
    else:
        form = form_class(instance=profile_obj)
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value
    
    return render_to_response(template_name,
                              { 'form': form,
                                'profile': profile_obj, },
                              context_instance=context)
edit_profile = login_required(edit_profile)

def profile_detail(request, username, public_profile_field=None,
                   template_name='profiles/profile_detail.html',
                   extra_context=None):
    """
    Detail view of a user's profile.
    
    If no profile model has been specified in the
    ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    If the user has not yet created a profile, ``Http404`` will be
    raised.
    
    **Required arguments:**
    
    ``username``
        The username of the user whose profile is being displayed.
    
    **Optional arguments:**

    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``public_profile_field``
        The name of a ``BooleanField`` on the profile model; if the
        value of that field on the user's profile is ``False``, the
        ``profile`` variable in the template will be ``None``. Use
        this feature to allow users to mark their profiles as not
        being publicly viewable.
        
        If this argument is not specified, it will be assumed that all
        users' profiles are publicly viewable.
    
    ``template_name``
        The name of the template to use for displaying the profile. If
        not specified, this will default to
        :template:`profiles/profile_detail.html`.
    
    **Context:**
    
    ``profile``
        The user's profile, or ``None`` if the user's profile is not
        publicly viewable (see the description of
        ``public_profile_field`` above).
    
    **Template:**
    
    ``template_name`` keyword argument or
    :template:`profiles/profile_detail.html`.
    
    """
    user = get_object_or_404(User, username=username)
    try:

spaceapps/templates/profiles/create_profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div id="content" class="row">
	<div class="twelve columns">
		<form method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="other_data row">
				<div class="data twelve columns">
					Looking to change your registration to a different venue, or can no longer attend? <a href="{% url 'registration:edit' %}">Change your Event</a> or <a href="{% url 'registration:delete' %}">Delete your Account</a>
					<fieldset>
						<legend>Should other people be allowed to contact you?</legend>
						<div class="field row">
							<div class="one column">
								<input id="id_allow_contact" name="allow_contact" type="checkbox" checked>
							</div>
							<div class="eleven columns">
								<label for="id_allow_contact">Allow other participants to contact me</label>
							</div>
							{{ form.allow_contact.errors }}
						</div>
					</fieldset>
					<fieldset>
						<legend>What kind of experience do you have</legend>
						<div class="field row">
							<div class="twelve columns">
								<label for="id_background">Background: *</label>
								{{ form.background }}
								{{ form.background.errors }}
							</div>
						</div>
					</fieldset>
					<fieldset>
						<legend>Where are you from?</legend>
						<div class="field">
							<label for="id_city">City:</label>
							{{ form.city }}
							{{ form.city.errors }}
						</div>

						<div class="field">
							<label for="id_state">State or Province:</label>
							{{ form.state }}
							{{ form.state.errors }}
						</div>

						<div class="field">
							<label for="id_country">Country:</label>
							{{ form.country }}
							{{ form.country.errors }}
						</div>
					</fieldset>
				</div>
			</div>
			<div class="row">
				<div class="twelve columns">
					<button type="submit" class="button">Submit</button>
				</div>
			</div>
		</form> 
	</div>
</div>
{% endblock %}

spaceapps/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div id="content" class="row">
	<div class="twelve columns">
		<form method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="other_data row">
				<div class="data twelve columns">
					Looking to change your registration to a different venue, or can no longer attend ? <a href="{% url 'registration:edit' %}">Change your Event</a> or <a href="{% url 'registration:delete' %}">Delete your Account</a>
					<fieldset>
						<legend>A little bit of information about you</legend>
						<div class="field row">
		  				 	<div class="six columns field">
								<label for="id_first_name">First name: *</label>
			  					 {{ form.first_name }}
								 {{ form.first_name.errors }}
			  			 	</div>

				   			<div class="six columns field">
								<label for="id_last_name">Last name: *</label>
				   				 {{ form.last_name }}
								 {{ form.last_name.errors }}
				   			 </div>
						 </div>
						 <div class="field row">
							 <div class="twelve columns">
		 						 <label for="id_email">E-mail: *</label>
		 					 	{{ form.email }}
		 					 	{{ form.email.errors }}
							</div>
						</div>
						<div class="field row">
							<div class="twelve columns">
								<a href="/account/password/change/">Change your password</a>
							</div>
						</div>
					</fieldset>
					<fieldset>
						<legend>Should other people be allowed to contact you?</legend>
						<div class="field row">
							<div class="one column">
								<input id="id_allow_contact" name="allow_contact" type="checkbox" checked>
							</div>
							<div class="eleven columns">
								<label for="id_allow_contact">Allow other participants to contact me</label>
							</div>
							{{ form.allow_contact.errors }}
						</div>
					</fieldset>
					<fieldset>
						<legend>What kind of experience do you have</legend>
						<div class="field row">
							<div class="twelve columns">
								<label for="id_background">Background: *</label>
								{{ form.background }}
								{{ form.background.errors }}
							</div>
						</div>
					</fieldset>
					<fieldset>
						<legend>Where are you from?</legend>
						<div class="field">
							<label for="id_city">City:</label>
							{{ form.city }}
							{{ form.city.errors }}
						</div>

						<div class="field">
							<label for="id_state">State or Province:</label>
							{{ form.state }}
							{{ form.state.errors }}
						</div>

						<div class="field">
							<label for="id_country">Country:</label>
							{{ form.country }}
							{{ form.country.errors }}
						</div>
					</fieldset>
				</div>
			</div>
			<div class="row">
				<div class="twelve columns">
					<button type="submit" class="button">Submit</button>
				</div>
			</div>
		</form> 
	</div>
</div>
{% endblock %}

spaceapps/templates/profiles/profile_detail.html
{% extends "base.html" %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div id="content" class="row">
	<div class="twelve columns">
		Thanks for updating your information!
	</div>
</div>
{% endblock %}

spaceapps/templates/profiles/profile_list.html
{% extends "base.html" %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div id="content" class="row">
	<div class="twelve columns">
		We don't have a list of registrants available yet, check back soon.
	</div>
</div>
{% endblock %}