spaceapps/core/urls.py
from django.conf.urls import patterns, url

from .views import (
    Home,
    Error,
    Lost,
    No,
    )


urlpatterns = patterns('',
    url(r'^$',
        Home.as_view(),
        ),
    url(r'^500$',
        Error.as_view(),
        ),
    url(r'^404$',
        Lost.as_view(),
        ),
    url(r'^403$',
        No.as_view(),
        ),
    )

spaceapps/locations/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (
    List,
    Sponsors,
    Streaming,
    Visualize,
    Detail,
    Edit,
    Attendees,
    CSV,
    Related,
    )


urlpatterns = patterns('',
    url(r'^$',
        List.as_view(),
        name='list',
        ),
    url(r'^(sponsor)/$',
        Sponsors.as_view(),
        name='sponsors',
        ),
    url(r'^(visualize)/$',
        Visualize.as_view(),
        name='visualize',
        ),
    url(r'^(streaming)/(?P<slug>[-_\w]+)/$',
        Streaming.as_view(),
        name='streaming',
        ),
    url(r'^(?P<slug>[-_\w]+)/$',
        Detail.as_view(),
        name='detail',
        ),
    url(r'^(?P<slug>[-_\w]+)/edit$',
        login_required(Edit.as_view()),
        name='edit',
        ),
    url(r'^(?P<slug>[-_\w]+)/attendees$',
        login_required(Attendees.as_view()),
        name='attendees',
        ),
    url(r'^(?P<slug>[-_\w]+)/related$',
        login_required(Related.as_view()),
        name='related',
        ),
    url(r'^(?P<slug>[-_\w]+)/csv$',
        login_required(CSV.as_view()),
        name='export',
        ),
    )

spaceapps/spaceapps/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import TemplateView

from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^selectable/', include('selectable.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls')),

    # url(r'^messages/', include('postman.urls')),
    # url(r'^notifications?/', include('notification.urls')),
    
    url(r'^account/', include('allauth.urls')),
    url(r'^challenges?/', include('challenges.urls', namespace='challenges')),
    url(r'^locations?/', include('locations.urls', namespace='locations')),
    url(r'^register/', include('registration.urls', namespace='registration')),
    url(r'^projects?/', include('projects.urls', namespace='projects')),
    url(r'^profiles?/', include('profiles.urls', namespace='profiles')),
    url(r'^awards?/', include('awards.urls', namespace='awards')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', TemplateView, { 'template': 'home.html' }),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

spaceapps/challenges/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Challenge(models.Model):
    title = models.CharField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=255, blank=True)
    slug = models.SlugField()
    description = models.TextField()
    category = models.ForeignKey('Category')
    internal = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    image = models.ImageField(upload_to="challenge", blank=True, null=True)

    class Meta:
        verbose_name_plural = "Challenges"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'view_challenge', 
            kwargs={'slug': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100, blank=True)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"
    
    def __unicode__(self):
        return self.name

class ChallengeSponsor(models.Model):
    challenge = models.ForeignKey(Challenge)
    name = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)

    def __unicode__(self):
        return self.name 

class ChallengeAuthor(models.Model):
    challenge = models.ForeignKey(Challenge)
    author = models.ForeignKey(User)
    is_public = models.BooleanField(default=False)

class ChallengeDataset(models.Model):
    challenge = models.ForeignKey(Challenge)
    title = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=200, blank=True)
    description = models.TextField()

    def __unicode__(self):
        return self.title

spaceapps/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class Background(models.Model):
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

BACKGROUND = (                                                              
        ('1', 'Developer'),                                                       
        ('2', 'Designer/Artist'),                                                   
        ('3', 'Student'),
        ('4', 'Subject Matter Expert'),
        ('5', 'Entrepreneur'),                                                   
    ) 

class Profile(models.Model):
    user = models.OneToOneField(User)
    allow_contact = models.BooleanField(default=False,
        help_text=('Designates that this user may be contacted by email.'))
    background = models.ManyToManyField(Background, blank=True)
    skype = models.CharField(max_length=32, blank=True)
    twitter = models.CharField(max_length=15, blank=True)
    github = models.CharField(max_length=32, blank=True)
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=32, blank=True)
    country = models.CharField(max_length=32, blank=True)

    class Meta:
        verbose_name = ('profile')
        verbose_name_plural = ('profiles')

    def __unicode__(self):
        return unicode(self.user)

spaceapps/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from challenges.models import Challenge

class Project(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()
    challenge = models.ForeignKey(Challenge, blank=True, null=True)
    source_url = models.URLField(max_length=200, blank=True)
    source_url_check_bypass = models.BooleanField(default=False)
    license = models.ForeignKey('License')
    video = models.URLField(max_length=200, blank=True)
    nominated = models.BooleanField(default=False) 
    remove_from_judging = models.BooleanField(default=False)
    reason_for_disqualification = models.TextField(
        max_length=500, 
        null=True, 
        default=None, 
        blank=True,
        )
    finalist = models.BooleanField(default=False)
    hashtag = models.CharField(
        max_length=100, 
        null=True, 
        default=None, 
        blank=True,
        )
    short_description = models.TextField(
        max_length=500, 
        null=True, 
        default=None, 
        blank=True,
        )

    class Meta:                                                                 
        verbose_name_plural = "Projects"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'projects:view_project', 
            kwargs={'slug': self.slug})

class License(models.Model):                                                   
    name = models.CharField(max_length=100, blank=True)                     
    url = models.URLField(max_length=200, blank=True)                          
                                                                                
    class Meta:                                                                 
        verbose_name_plural = "Licenses"
    
    def __unicode__(self):                                                      
        return self.name                                                    

class Team(models.Model):
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    request_text = models.TextField(blank=True)
    approved = models.BooleanField(default=False)
    
    class Meta:                                                                 
        verbose_name_plural = "Team"

class Resource(models.Model):                                           
    project = models.ForeignKey(Project)                                    
    title = models.CharField(max_length=100, blank=True)                        
    url = models.URLField(max_length=200, blank=True)                          
                                                                                
    class Meta:                                                                 
        verbose_name_plural = "Resources"
    
    def __unicode__(self):                                                      
        return self.title

spaceapps/locations/forms.py
from django.forms import Form, ModelForm, CharField, ChoiceField
from django.forms.models import (
    modelformset_factory, 
    inlineformset_factory, 
    BaseInlineFormSet,
    )
from django.forms.formsets import formset_factory, BaseFormSet

import selectable.forms as selectable
from awards.models import LocalAward, Nomination
from registration.models import Registration
from projects.models import Project

from .lookups import UserLookup
from .models import (
    Location, 
    Sponsor,
    Lead,
    Resource,
    )


class LocalAwardForm(Form):
    def __init__(self, projects, *args, **kwargs):
        super(LocalAwardForm, self).__init__(*args, **kwargs)
        self.fields['project'] = ChoiceField(choices=projects)

    choices=(('1', 'First',))

    title = CharField(max_length=100)
    project = ChoiceField(choices=choices)

class LocationForm(ModelForm):
    class Meta:
        model = Location 
        exclude = ('name', 'slug', 'private', 'start', 'end' )

class LeadForm(ModelForm):
    class Meta(object):
        model = Lead
        widgets = {
            'lead': selectable.AutoCompleteSelectWidget(
                lookup_class=UserLookup)
            }

class CheckInForm(ModelForm):
    test = 'happy'

    class Meta(object):
        model = Registration
        # fields = ('check_in', )

CheckInFormSet = modelformset_factory(
        Registration,
        form=CheckInForm,
        extra=0,
        )

SponsorFormSet = inlineformset_factory(
        Location, 
        Sponsor, 
        extra=1,
        )

LeadFormSet = inlineformset_factory(
        Location,
        Lead,
        form=LeadForm,
        extra=1,
        )

ResourceFormSet = inlineformset_factory(
        Location,
        Resource,
        extra=1,
        )

class LocalAwardBaseFormSet(BaseFormSet):
    def __init__(self, projects, *args, **kwargs):
        self.projects = projects
        super(LocalAwardBaseFormSet, self).__init__(*args, **kwargs)

    def _construct_forms(self):
        self.forms = []
        for i in xrange(self.total_form_count()):
            self.forms.append(self._construct_form(i, projects=self.projects))

LocalAwardFormSet = formset_factory(
    LocalAwardForm, 
    formset=LocalAwardBaseFormSet, 
    extra=1,
    )

class AwardBaseFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        self.projects = kwargs.pop('projects')
        super(AwardBaseFormSet, self).__init__(*args, **kwargs)

    def _construct_forms(self):
        self.forms = []
        for i in xrange(self.total_form_count()):
            self.forms.append(self._construct_form(i, projects=self.projects))

class AwardForm(ModelForm):
    class Meta:
        model = LocalAward

    def __init__(self, *args, **kwargs):
        projects = kwargs.pop('projects')
        super(AwardForm, self).__init__(*args, **kwargs)
        if projects is not None:
            self.fields['project'].queryset = Project.objects.filter(
                id__in=projects).distinct()

AwardFormSet = inlineformset_factory(
        Location,
        LocalAward,
        form=AwardForm,
        formset=AwardBaseFormSet,
        extra=1,
        ) 

class NominationForm(ModelForm):
    class Meta:
        model = LocalAward

    def __init__(self, *args, **kwargs):
        projects = kwargs.pop('projects')
        super(NominationForm, self).__init__(*args, **kwargs)
        if projects is not None:
            self.fields['project'].queryset = Project.objects.filter(
                id__in=projects).distinct()
        
NominationFormSet = inlineformset_factory(
    Location,
    Nomination,
    form=NominationForm,
    formset=AwardBaseFormSet,
    extra=2,
    max_num=2,
    )

spaceapps/templates/locations/location_admin.html
{% extends 'base.html' %}
{% block content %}

{% comment %}

<h3>Location</h3>

<p>{{ location.name }}</p>
<p>{{ location.description }}</p>
<p>{{ location.city }}</p>
<p>{{ location.capacity }}</p>

<h3>Registered Attendees</h3>

{% for i in attendees %}
<p>{{ i.user }}</p>
{% endfor %}

<h3>Location Leads</h3>

{% for i in leads %}
<p>{{ i.lead }}</p>
{% endfor %}

<h3>Location Sponsors</h3>

{% for i in sponsors %}
<p>{{ i }}</p>
{% endfor %}

<h3>Location Resources</h3>

{% for i in resources %}
<p>{{ i }}</p>
{% endfor %}

spaceapps/templates/locations/location_attendees.html
{% extends "base.html" %}

{% block content %}
<div id="content" class="row">
	
	<div class="twelve columns">
		<h3>Your Attendees</h3>
		{% if attendees %}
		<table class="twelve">
		  <thead>
		    <tr>
				<th>#</th>
		      <th>First Name</th>
		      <th>Last Name</th>
		      <th>Email Address</th>
		      <th>Residency</th>
			  <th>Background</th>
		    </tr>
		  </thead>
		  <tbody>
			  {% for i in attendees %}
			  <tr>
				  <td class="count"><span>{{ forloop.counter }}</span></td>
				  <td>{{ i.user.first_name }}</td>
				  <td>{{ i.user.last_name }}</td>
				  <td><a href="mailto:{{ i.user.email }}">{{ i.user.email }}</a></td>
				  <td>{% if i.user.get_profile.city %}{{ i.user.get_profile.city }}{% endif %}{% if i.user.get_profile.state %}{% if i.user.get_profile.city %}, {% endif %}{{ i.user.get_profile.state }}{% endif %}{% if i.user.get_profile.country %}, {{ i.user.get_profile.country }}{% endif %}</td>
				  <td>{% for background in i.user.get_profile.background.all %}
					  {{ background }}
					  {% endfor %}
				  </td>
			  </tr>
			  {% endfor %}
		  </tbody>
		</table>
		{% else %}
		<p>Sorry, there are no attendees registered for your venue!</p>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
  var numReg = $("td.count:last").text();
  $('h3').after('<p id="numReg">You have ' + numReg + ' participants registered.</p>');
});
</script>
{% endblock js %}


{% comment %}
{% if i.check_in %}
User checked in
{% else %}
User not checked in
{% endif %}
{% endcomment %}

spaceapps/templates/locations/location_award_form.html
{% extends 'base.html' %}
{% block content %}
<form enctype="multipart/form-data" method='post' action=''>                    
    {% csrf_token %}
    {{ form }}
<input type='submit' class='button' value='Submit'>                           
</form>
{% endblock %}

spaceapps/templates/locations/location_checkin.html
{% extends 'base.html' %}
{% block content %}
<form enctype="multipart/form-data" method='post' action=''>                    
    {% csrf_token %}
{% for i in form %}
{{ i.user }}                                                      
{{ i.check_in }}
{{ i.test }}
{% endfor %}
<input type='submit' class='button' value='Submit'>                           
</form>
{% endblock %}

spaceapps/templates/locations/location_form.html
{% extends 'base.html' %}

{% block title %}Edit Location{% endblock title %}

{% block content %}
{{ lead_form.media.css }}
<div id="content" class="location row uncontain">
	<div class="twelve columns">
	<dl class="tabs contained">
	  <dt>{{ location.city }}</dt>
	  <dd class="active"><a href="#overview">Overview</a></dd>
	  <dd><a href="#edit">Edit Information & Awards</a></dd>
	  <dd><a href="#attendees">View Attendees</a></dd>
	  <dd><a href="/location/{{ location.slug }}">View Location Page</a></dd>
	</dl>
	<div class="row">
	<ul class="tabs-content contained backfill twelve columns">
	  <li class="active" id="overviewTab">
		  <h2 class="welcome">Hi, {{ request.user.first_name }}!</h3>	
		  <p><b>{{ location.city }} currently has <span class="registrants_number">(loading)</span> registrants.</b><br></p>
		  <hr>
		  <div class="row">
			  <div class="twelve columns">
				  <div class="radius progress  {% if location.is_full %}alert{% else %}success{% endif %} eight" id="registrant_progress"><span class="meter"></span></div>
				  <b>Current Registrations (<span class="registrants_number">(loading)</span>/{{ location.capacity }})</b><br>
				  Registration is currently {% if not location.open %}<b>closed</b>{% elif location.is_full %}<b>sold out</b>{% elif location.open %}<b>open</b>{% endif %}
				  {% if location.is_full %}<p><br><span class="alert label">Waitlist Information</span><br>A waitlist has been created for your venue. <b>This list does not update automatically</b>. Once you have raised the maximum capacity of your venue, <a href="/location/{{ location.slug }}/waitlist">click here</a> to download a CSV file of the email addresses of every person on the waitlist. You will then need to email them and notify them that additional spots are available!</p>{% endif %}
	  </li>
	  <li id="editTab" class="location edit">
  		<form enctype="multipart/form-data" method='post' action='' class="custom">
  		{% csrf_token %}
  			<div class="field noinput">
  			 {{ form.name.errors }}
  			 <div class="noinput_detail"><span class="loc_name">{{ location.name }}</span>{{form.name }}</div>
  			 
  		 </div>
		 
		 
   		<div class="field slug noinput">
  			{{ form.slug.errors }}
  			<label for="id_slug">Page URL:</label>
  		 <div class="noinput_detail"><a href="/{{ location.slug }}">/location/{{ location.slug }}</a>{{form.slug }}</div>
  	 </div>
		 
  		 <h3>Venue Details</h3>
		 
  		<div class="field image_upload">
  			 {{ form.image.errors }}
  			 <label for="id_image">Header Image <i>(1000px wide, 425px tall. Please ensure you have rights to use and that the image is optimized for file size!)</i>:</label>
  			 {{ form.image }}
  		 </div>
			 
   		<div class="field">
   			 {{ form.description.errors }}
   			 <label for="id_name">Venue Description:</label>
  			 <div id="wysihtml5-toolbar" style="display: none;">
  				 <div id="toolbar-styling" class="eight columns">
  					 <a data-wysihtml5-command="bold"><i class="icon-bold"></i> bold</a>
  					 <a data-wysihtml5-command="italic"><i class="icon-italic"></i> italic</a>
  					 <a data-wysihtml5-command="insertOrderedList"><i class="icon-list-ol"></i> insert ordered list</a>
  					 <a data-wysihtml5-command="insertUnorderedList"><i class="icon-list-ul"></i> insert unordered list</a>
  					 <a data-wysihtml5-command="createLink"><i class="icon-link"></i> insert link</a>
  					 <div data-wysihtml5-dialog="createLink" style="display: none;">
  						 <label>
  							 Link:
  							 <input data-wysihtml5-dialog-field="href" value="http://" class="text">
  						 </label>
  						 <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
  					 </div>
  				 </div>
  				 <div class="two columns offset-by-two">
  					 <a data-wysihtml5-action="change_view" href="javascript:;" unselectable="on" class="wysihtml5-action-active" id="htmlswitch">switch to html</a>
  				 </div>
  			 </div>
  			 {{ form.description }}
  		 </div>
		 
		 
  		 <h3>Venue Location</h3>
		 
    		<div class="field">
    			 {{ form.street.errors }}
    			 <label for="id_street">Venue Street:</label>
    			 {{ form.street }}
  			  {{ form.street2.errors }}
    			 <label for="id_street2">Venue Street Line 2:</label>
    			 {{ form.street2 }}
  			 <div class="row">
  				 <div class="six columns">
  					  {{ form.city.errors }}
  		  			 <label for="id_street">City:</label>
  		  			 {{ form.city }}
  				 </div>
  				 <div class="three columns">
  					  {{ form.state.errors }}
  		  			 <label for="id_state">State or Province:</label>
  		  			 {{ form.state }}
  				 </div>
  				 <div class="three columns">
  					  {{ form.postal.errors }}
  		  			 <label for="id_postal">Postal Code:</label>
  		  			 {{ form.postal }}
  				 </div>
  			 </div>
  			 <div class="row">
  				 <div class="four columns">
  					  {{ form.country.errors }}
  		  			 <label for="id_country">Country:</label>
  		  			 {{ form.country }}
  				 </div>
  				 <div class="two columns">
  					  {{ form.continent.errors }}
  		  			 <label for="id_continent">Continent:</label>
  		  			 {{ form.continent }}
  				 </div>
  		  		<div class="six columns">
  		  			 {{ form.timezone.errors }}
  		  			 <label for="id_timezone">Timezone:</label>
  		  			 {{ form.timezone }}
  		  		 </div>
  			 </div>
  			 <div class="row">
  				 <div class="three columns">
  					  {{ form.lat.errors }}
  		  			 <label for="id_lat">Latitude <i>(decimal format)</i>:</label>
  		  			 {{ form.lat }}
  				 </div>
  				 <div class="three columns end">
  					  {{ form.lon.errors }}
  		  			 <label for="id_lon">Longitude <i>(decimal format)</i>:</label>
  		  			 {{ form.lon }}
  				 </div>
  			 </div>
    		 </div>
		
		 
  		 <h3>Event Information</h3>
		 
  		 <div class="field row">
  			 <div class="four columns end">
  				  {{ form.capacity.errors }}
  	  			 <label for="id_capacity">Maximum Capacity (registration limit):</label>
  	  			 {{ form.capacity }}
  			 </div>
  		 </div>
		 
  		 <div class="field row">
  			 <div class="four columns end">
  				  {{ form.open.errors }}
  		         <label for="id_open">{{ form.open }}<span class="custom checkbox"></span> Open for Registration</label>
  				 <a href="/location/{{ location.slug }}/attendees">See list of Current Attendees</a>
  			 </div>
  		 </div>
		 
		 <div class="field row">
			 
		 </div>
		 
  		 <h3>Sponsors</h3>
		 <p>Please ensure you have rights to use and that the image is optimized for file size!</p>
  		 <div class="sponsors">
  			{{ sponsor_form.management_form }}
  				{% for form in sponsor_form %}
  					<div id='sponsor' class='sortable'>
  						{{ form.as_p }}
  					</div>
  					{% endfor %}
  		</div>
		
		
  	 <h3>Leads</h3>

	 <p><b>Curious why your avatar isn't appearing?</b> Associate your email address with <a href="http://gravatar.com">Gravatar</a>!</p>
  	 <div class="leads" style="display:none;">
  		 {{ lead_form.management_form }}
  		 {% for form in lead_form %}
  		 <div id='lead'>
  			 {{ form.as_p }}
  		 </div>
  			{% endfor %}
  	</div>


  <p>You may create an unlimited number of Local Awards (for instance, 1st Place, Best use of Data, etc), and select two projects to forward on to Global Judging.</p>
	<h3>Local Awards</h3>
	{{ localaward_form.management_form }}
	<div class="localaward_form">
	{% for form in localaward_form %}
		<div class="localaward">
			{{ form.as_p }}
		</div>
	{% endfor %}
	</div>
	
	<h3>Global Nomination</h3>
	{{ nomination_form.management_form }}  
	<div class="globalnom_form">                                     
	{% for form in nomination_form %}                                           
		<div class="nomination">                                                       
			{{ form.as_p }}                                                           
		</div>                                                                      
    {% endfor %}
	</div>
	
	
  	<h3>Resources</h3>
	<p>You can name URLs "Twitter", "Facebook", or "Blog" to enable special features </p>
  	<div class="resources">
  		{{ resource_form.management_form }}
  		{% for form in resource_form %}
  			<div id='resource'>
  		{{ form.as_p }}
  			</div>
  		{% endfor %}
  	</div>
  		<input type='submit' class='button' value='Submit'>
  		</form>
	  </li>
	  <li id="attendeesTab">
		  <div id="attendees_table">Loading</div>
		  <p><a href="/location/{{ location.slug }}/csv">Download as CSV file</a></p>
	  </li>
	</ul>
</div>
</div>
</div><!-- #content -->

<script src='/static/js/jquery.formset.min.js'></script>
<script src='/static/js/jquery.sortable.min.js'></script>
<script type="text/javascript">
  $(function() {
    $('#sponsor').formset({ 
      prefix: '{{ sponsor_form.prefix }}' 
    }); 
    $('#lead').formset({
      prefix: '{{ lead_form.prefix }}',
      added: function(row) {
                        bindSelectables($(row));
                }
    });
    $('.localaward').formset({ 
      prefix: '{{ localaward_form.prefix }}' 
    }); 
    $('#resource').formset({ 
      prefix: '{{ resource_form.prefix }}' 
    }); 
  })
</script>
<script>
    $('.sortable').sortable();
</script>
{{ lead_form.media.js }}
{% endblock %}

{% block js %}
	<script type="text/javascript">
		$(document).ready(function() {
			$("#htmlswitch").click(function () {
			      $("textarea#id_description").toggleClass("html");
				  $("#toolbar-styling").toggle();
			    });
		});
	</script>
	<script>
	  $(document).ready(function() {
	      $('span.registrants_number').load('/locations/{{ location.slug }}/attendees td.count:last span', function(result) {
			  var registrants = $('span.registrants_number:first').text();
			  var total_spots = '{{ location.capacity}}';
			  var bar_width = (registrants / total_spots) * 100;
			  var bar_width_percent = bar_width + '%';
			  $('#registrant_progress span.meter').css("width",bar_width_percent);
	      });
	  });
	</script>
	<script type="text/javascript">
	  $(document).ready(function() {
	      $('#attendees_table').load('/locations/{{ location.slug }}/attendees table');
	  });
	</script>
	<script type="text/javascript">
	$(document).ready(function() {
		$('a.add-row,a.delete-row').addClass('button');
  });
	  
	</script>
	<script type="text/javascript">
	  $("div.sponsors div").click(function() {
		  if ( !$(this).find('p:nth-of-type(4) input').val() )  {
		 	 var number_of_sponsors = $('div.sponsors div').length;
			 $(this).find('p:nth-of-type(4) input').val(number_of_sponsors);
		 }
		 else {
			 return;
		 }
	  });
	  
	</script>
	
	<script src="/static/js/wysihtml5/advanced.js"></script>
	<script src="/static/js/wysihtml5/wysihtml5-0.3.0.min.js"></script>
	<script>
	var editor = new wysihtml5.Editor("id_description", { // id of textarea element
	  toolbar:      "wysihtml5-toolbar", // id of toolbar element
	  parserRules:  wysihtml5ParserRules // defined in parser rules set 
	});
	</script>
	<script type="text/javascript">
	$(document).ready(function() {
		var header_image = $("div.image_upload a").attr("href");
	  	$("label[for='id_image']").after("<img src='" + header_image +"' alt='Header Image'>");
		$("div.image_upload a").after("<br>");
		$("#id_image").live("change", function(){
			$('div.image_upload img').remove();
			$("label[for='id_image']").after("<div class='alert-box secondary'>Save the form to view your upload image.</div>");
		});
	});
	</script>
{% endblock %}

spaceapps/templates/locations/location_sponsors.html
{% block content %}
<h3>Location Sponsors</h3>
<div class="location_sponsor_list">
{% for i in object_list|dictsort:"city" %}
{% if i.slug == "virtual" %}
{% else %}
<h4><a href="{% url 'locations:detail' i.slug %}">{{ i.city }}</a></h4>
{% for i in i.sponsor_set.all %}
{% if forloop.first %}
<ul>
{% endif %}
<li><a href="{{ i.url }}" target="_blank">{{ i.name }}</a></li>
{% if forloop.last %}
</ul>
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
</div>
{% endblock %}

spaceapps/templates/locations/location_streaming.html
<div class="{{ object.slug }} {% for i in object.resource_set.all %}{% if i.name == "Ustream" %}streaming{% endif %}{% endfor %} flex-video">
	 {% for i in object.resource_set.all %}
	 {% if i.name == "Ustream" %}
	<iframe src="http://www.ustream.tv/embed/{{ i.url }}" width="608" height="368" scrolling="no" frameborder="0" style="border: 0px none transparent;"></iframe><br /><a href="http://www.ustream.tv/producer" style="padding: 2px 0px 4px; width: 400px; background: #ffffff; display: block; color: #000000; font-weight: normal; font-size: 10px; text-decoration: underline; text-align: center;" target="_blank">Free desktop streaming application by Ustream</a>
	{% endif %}
	{% endfor %}
</div>